"""Drift gate for the generated IDS schema tables.

`crates/core/src/ids/schema_tables.rs` is generated by
`scripts/gen_schema_tables.py` from ifcopenshell (pinned version) and
committed. This test regenerates it into a temp path and asserts the
committed file is byte-identical, so a hand edit or a stale regeneration
fails CI.

Skips unless ifcopenshell at the pinned version is importable —
ifcopenshell is a generation-time dependency only, never a runtime one.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
GEN = REPO / "scripts" / "gen_schema_tables.py"
COMMITTED = REPO / "crates" / "core" / "src" / "ids" / "schema_tables.rs"
PINNED = "0.8.5"

ifcopenshell = pytest.importorskip("ifcopenshell")
if ifcopenshell.version != PINNED:
    pytest.skip(
        f"ifcopenshell {ifcopenshell.version} != pinned {PINNED}",
        allow_module_level=True,
    )


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_schema_tables", GEN)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def test_schema_tables_match_generator(tmp_path):
    gen = _load_generator()
    out = tmp_path / "schema_tables.rs"
    gen.main(["--out", str(out)])
    assert COMMITTED.exists(), f"{COMMITTED} missing — run {gen.GEN_COMMAND}"
    assert out.read_bytes() == COMMITTED.read_bytes(), (
        f"{COMMITTED.relative_to(REPO)} drifted from the generator; "
        f"re-run `{gen.GEN_COMMAND}` and commit the result"
    )
