"""One-shot codegen: dump per-schema IFC entity supertype maps.

ifcfast's `classify.py` used to soft-import ``ifcopenshell`` to resolve
an entity's ancestor chain (needed when the classifier's explicit
COUNT/MEASURE/LINEAR/SKIP whitelists miss an entity and the fallback
has to ask "does X ultimately descend from IfcFlowTerminal?").

The IFC schemas are static published standards — IFC2x3, IFC4, IFC4x3.
Their inheritance chains never change at runtime. So we can extract
them ONCE at build time, commit the result as a literal Python dict,
and drop the runtime ``ifcopenshell`` dependency entirely.

Run this script when a new IFC schema lands (or when ``ifcopenshell``
gains a new supported schema version):

    python scripts/gen_schema_supertypes.py \\
        > python/ifcfast/data/schema_supertypes.py

The generated module exports ``SUPERTYPE: dict[str, dict[str, str]]``
keyed by schema name → entity name → immediate supertype name.
``IfcRoot`` (and any other top-level entity) has no entry — the
classifier reads "missing" as "no further parent".

It also exports ``ALL_ENTITIES: frozenset[str]`` — every entity
declaration name across all supported schemas, *including* the
supertype-less roots (IfcPerson, IfcOwnerHistory, IfcGridAxis, …) that
SUPERTYPE structurally omits. Entity-name validation (GH #71) must
check this set, not SUPERTYPE: a valid root entity is not a typo
(PR #85 review F1).
"""

from __future__ import annotations

import sys

import ifcopenshell

SCHEMAS: tuple[str, ...] = ("IFC2X3", "IFC4", "IFC4X3")


def supertypes_for(schema: str) -> dict[str, str]:
    """Return ``{entity_name: supertype_name}`` for every entity in the
    schema that has a supertype. Entities at the inheritance root
    (``IfcRoot`` is the obvious one, plus a handful of grammar-internal
    abstracts) are omitted — the classifier reads missing keys as
    "no further parent" and terminates the walk."""
    sch = ifcopenshell.schema_by_name(schema)
    out: dict[str, str] = {}
    for decl in sch.declarations():
        # The schema's declaration table includes TYPE / ENUM / SELECT
        # declarations too. Only entity declarations have a supertype
        # chain worth following. `as_entity()` returns None for the
        # non-entity flavours.
        try:
            entity = decl.as_entity()
        except AttributeError:
            continue
        if entity is None:
            continue
        sup = entity.supertype()
        if sup is None:
            continue
        out[entity.name()] = sup.name()
    return out


def entity_names_for(schema: str) -> set[str]:
    """Every entity declaration name in the schema — including the
    supertype-less roots that ``supertypes_for`` omits."""
    sch = ifcopenshell.schema_by_name(schema)
    out: set[str] = set()
    for decl in sch.declarations():
        try:
            entity = decl.as_entity()
        except AttributeError:
            continue
        if entity is None:
            continue
        out.add(entity.name())
    return out


def main() -> None:
    print('"""Per-schema IFC entity → immediate-supertype map.')
    print()
    print("Generated by scripts/gen_schema_supertypes.py — DO NOT EDIT BY HAND.")
    print("Re-run that script when ifcopenshell's schema bundle changes.")
    print()
    print(f"Source: ifcopenshell {ifcopenshell.version}")
    print(f"Schemas: {', '.join(SCHEMAS)}")
    print('"""')
    print()
    print("from __future__ import annotations")
    print()
    print("SUPERTYPE: dict[str, dict[str, str]] = {")
    for schema in SCHEMAS:
        m = supertypes_for(schema)
        print(f"    {schema!r}: {{")
        for entity in sorted(m):
            print(f"        {entity!r}: {m[entity]!r},")
        print("    },")
    print("}")
    print()
    print("# Every entity name across all supported schemas, including the")
    print("# supertype-less roots SUPERTYPE omits. The vocabulary for")
    print("# entity-name validation (GH #71, PR #85 review F1).")
    print("ALL_ENTITIES: frozenset[str] = frozenset({")
    union: set[str] = set()
    for schema in SCHEMAS:
        union |= entity_names_for(schema)
    for entity in sorted(union):
        print(f"    {entity!r},")
    print("})")


if __name__ == "__main__":
    main()
