"""One-shot codegen: canonical spelling of every IFC defined / enumeration type.

Writes ``crates/core/src/extractors/defined_type_names.rs`` — one sorted
static table ``(UPPERCASE STEP token, canonical CamelCase name)`` holding
every defined type (``TYPE IfcXxx = …``) and every enumeration type of
IFC2X3, IFC4 and IFC4X3_ADD2, unioned. A STEP value wrapper
(``IFCPRESSUREMEASURE(2.5)``) is always a defined type, and an IDS
``dataType`` is a defined or an enumeration type, so this is the spelling
table for:

* ``psets.value_type`` (GH #195: ``IfcPressureMeasure``, not the
  single-word title case ``IfcPressuremeasure``), and
* the IDS ``PROP_DATATYPE_MISMATCH`` ``actual`` string (GH #200:
  ``IfcText`` like IfcTester, not the STEP token ``IFCTEXT``).

Kept out of ``ids/schema_tables.rs`` on purpose: the ``ids`` feature is
optional and the public tables must build without it
(``--no-default-features --features csg``). A defined type is spelled the
same in every schema that has it (the generator asserts this), so one
union table serves all three.

Same sanctioned pattern as ``scripts/gen_schema_tables.py``: ifcopenshell
is a generation-time dependency only; the output is committed and
``tests/test_defined_type_names_drift.py`` regenerates and byte-compares.

    .venv/bin/python scripts/gen_defined_type_names.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import NoReturn

import ifcopenshell

PINNED_IFCOPENSHELL = "0.8.5"

SCHEMAS: tuple[tuple[str, str], ...] = (
    ("IFC2X3", "IFC2X3"),
    ("IFC4", "IFC4"),
    ("IFC4X3", "IFC4X3_ADD2"),
)

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "crates" / "core" / "src" / "extractors" / "defined_type_names.rs"
GEN_COMMAND = ".venv/bin/python scripts/gen_defined_type_names.py"


def die(msg: str) -> NoReturn:
    print(f"gen_defined_type_names: {msg}", file=sys.stderr)
    sys.exit(1)


def collect() -> dict[str, str]:
    if ifcopenshell.version != PINNED_IFCOPENSHELL:
        die(f"ifcopenshell {ifcopenshell.version} != pinned {PINNED_IFCOPENSHELL}")
    names: dict[str, str] = {}
    for name, expected in SCHEMAS:
        sch = ifcopenshell.schema_by_name(name)
        if sch.name() != expected:
            die(f"schema_by_name({name!r}) resolved to {sch.name()!r}, expected {expected!r}")
        for d in sch.declarations():
            if d.as_type_declaration() is None and d.as_enumeration_type() is None:
                continue
            n = d.name()
            up = n.upper()
            prev = names.get(up)
            if prev is not None and prev != n:
                die(f"{up} is spelled {prev!r} in one schema and {n!r} in {expected}")
            names[up] = n
    if not names:
        die("no types found")
    return names


def render(names: dict[str, str]) -> str:
    out = [
        "//! Canonical spelling of every IFC defined and enumeration type (IFC2X3 ∪ IFC4 ∪ IFC4X3_ADD2).",
        "//!",
        f"//! Generated by scripts/gen_defined_type_names.py from ifcopenshell {PINNED_IFCOPENSHELL} — DO NOT EDIT BY HAND",
        "//!",
        "//! Regenerate with:",
        "//!",
        "//! ```text",
        f"//! {GEN_COMMAND}",
        "//! ```",
        "//!",
        "//! `tests/test_defined_type_names_drift.py` regenerates and byte-compares.",
        "//! Consumers: `psets.value_type` (GH #195) and the IDS dataType-mismatch",
        "//! `actual` string (GH #200), via [`super::type_names`].",
        "",
        "/// `(UPPERCASE STEP token, canonical name)`, sorted by the first column.",
        "#[rustfmt::skip]",
        "pub(crate) static DEFINED_TYPE_NAMES: &[(&str, &str)] = &[",
    ]
    for up in sorted(names):
        out.append(f'    ("{up}", "{names[up]}"),')
    out.append("];")
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args(argv)
    names = collect()
    text = render(names)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} ({len(names)} defined + enumeration types)", file=sys.stderr)


if __name__ == "__main__":
    main()
