//! Minimal Wavefront `.obj` writer for visual validation.
//!
//! Per-product mesh emitted as a `g <entity>_<guid>` group, so users can
//! split / filter in Blender by element. No materials, no normals (the
//! viewer can compute face normals on load).

use std::io::{self, BufWriter, Write};

use crate::mesh::ProductMesh;

pub fn write<W: Write>(meshes: &[ProductMesh], out: &mut W) -> io::Result<()> {
    let mut w = BufWriter::with_capacity(1 << 20, out);
    writeln!(w, "# Generated by ifcfast-mesh (https://github.com/EdvardGK/ifc-workbench)")?;
    writeln!(w, "# {} products", meshes.len())?;

    // Per-product vertex offsets. OBJ vertices are 1-indexed and shared
    // across the whole file, so we accumulate.
    let mut vertex_base: u32 = 1;

    for mesh in meshes {
        let safe_guid: String = mesh
            .guid
            .chars()
            .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
            .collect();
        writeln!(w, "g {}_{}", mesh.entity, safe_guid)?;
        writeln!(w, "o {}_{}", mesh.entity, safe_guid)?;

        for chunk in mesh.vertices.chunks_exact(3) {
            writeln!(w, "v {} {} {}", chunk[0], chunk[1], chunk[2])?;
        }
        let n_verts = (mesh.vertices.len() / 3) as u32;
        for tri in mesh.indices.chunks_exact(3) {
            writeln!(
                w,
                "f {} {} {}",
                vertex_base + tri[0],
                vertex_base + tri[1],
                vertex_base + tri[2]
            )?;
        }
        vertex_base += n_verts;
    }

    w.flush()?;
    Ok(())
}
