//! IFC EXPRESS attribute indices (generated by `scripts/gen_attribute_schema.py`).

use std::collections::HashMap;
use std::sync::OnceLock;

static IFC4: OnceLock<HashMap<String, HashMap<String, u8>>> = OnceLock::new();
static IFC2X3: OnceLock<HashMap<String, HashMap<String, u8>>> = OnceLock::new();

fn load_ifc4() -> &'static HashMap<String, HashMap<String, u8>> {
    IFC4.get_or_init(|| parse_attr_json(include_str!("data/ifc4_attrs.json")))
}

fn load_ifc2x3() -> &'static HashMap<String, HashMap<String, u8>> {
    IFC2X3.get_or_init(|| parse_attr_json(include_str!("data/ifc2x3_attrs.json")))
}

fn parse_attr_json(raw: &str) -> HashMap<String, HashMap<String, u8>> {
    let parsed: HashMap<String, HashMap<String, u8>> =
        serde_json::from_str(raw).expect("attribute index JSON");
    parsed
}

fn map_for_schema(schema: &str) -> &'static HashMap<String, HashMap<String, u8>> {
    let u = schema.to_ascii_uppercase();
    if u.contains("IFC2X3") || u == "IFC2X3" {
        load_ifc2x3()
    } else {
        load_ifc4()
    }
}

/// Argument index for `entity`'s explicit attribute `attr` (EXPRESS order).
pub fn attribute_index(schema: &str, entity: &str, attr: &str) -> Option<u8> {
    let ent = entity.trim().to_ascii_uppercase();
    let map = map_for_schema(schema).get(&ent)?;
    map.get(attr).copied()
}

/// Attribute names for pattern matching (owned strings).
pub fn entity_attribute_name_list(schema: &str, entity: &str) -> Vec<String> {
    let ent = entity.trim().to_ascii_uppercase();
    let Some(map) = map_for_schema(schema).get(&ent) else {
        return Vec::new();
    };
    map.keys().cloned().collect()
}
